[package]
name = "todo-app-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
# you can check the latest version here: https://crates.io/crates/yew
dotenv = "0.15.0"
yew = "0.18"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
